Repository 100-hours-a-week/5-team-HRTH-ustock-fe, pull requests merged in 2024-08, with the labels that each got.

#5 Feature/elle - Chore : 개발환경 셋팅
  .github/workflows/cicd.yml
  .gitignore
  Dockerfile
  hth/README.md
  hth/src/App.test.tsx
  hth/src/logo.svg
  nginx.conf
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.tsx
  src/Component/chart.tsx
  src/Pages/home.tsx
  src/Router.tsx
  src/Styles/Colors.ts
  src/Styles/Fonts.ts
  src/Styles/GlobalStyles.ts
  src/constants/interface.ts
  src/constants/stock.ts
  src/custom.d.ts
  src/fonts/SCDream1.otf
  src/fonts/SCDream2.otf
  src/fonts/SCDream3.otf
  src/fonts/SCDream4.otf
  src/fonts/SCDream5.otf
  src/fonts/SCDream6.otf
  src/fonts/SCDream7.otf
  src/fonts/SCDream8.otf
  src/fonts/SCDream9.otf
  src/fonts/fonts.css
  src/img/Gukbap.png
  src/img/candy.png
  src/img/chart.png
  src/img/chicken.png
  src/img/home.png
  src/img/iphone.png
  src/img/loudly.png
  src/img/myProtfolioImg.png
  src/img/person.png
  src/img/portfolio.png
  src/img/profolioImg.png
  src/img/shutUp.png
  src/img/skrr_calculator.png
  src/index.css
  src/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
Labels: chore

#6 Dev - 개발환경 세팅 올립니다 ~
  hth/src/App.tsx
  package-lock.json
  package.json
  src/App.test.tsx
  src/App.tsx
  src/Component/chart.tsx
  src/Pages/home.tsx
  src/Router.tsx
  src/Styles/Colors.ts
  src/Styles/Fonts.ts
  src/Styles/GlobalStyles.ts
  src/constants/interface.ts
  src/constants/stock.ts
  src/custom.d.ts
  src/fonts/SCDream1.otf
  src/fonts/SCDream2.otf
  src/fonts/SCDream3.otf
  src/fonts/SCDream4.otf
  src/fonts/SCDream5.otf
  src/fonts/SCDream6.otf
  src/fonts/SCDream7.otf
  src/fonts/SCDream8.otf
  src/fonts/SCDream9.otf
  src/fonts/fonts.css
  src/img/Gukbap.png
  src/img/candy.png
  src/img/chart.png
  src/img/chicken.png
  src/img/home.png
  src/img/iphone.png
  src/img/loudly.png
  src/img/myProtfolioImg.png
  src/img/person.png
  src/img/portfolio.png
  src/img/profolioImg.png
  src/img/shutUp.png
  src/img/skrr_calculator.png
  src/index.tsx
Labels: chore

#10 Feature/veronica
  package-lock.json
  package.json
  src/Component/Carousel/EmblaCarousel.tsx
  src/Component/Carousel/EmblaCarouselArrowButtons.tsx
  src/Component/Carousel/EmblaCarouselDotButton.tsx
  src/Component/Carousel/base.css
  src/Component/Carousel/embla.css
  src/Component/List/MyStockItem.tsx
  src/Component/List/MyStockItemStyle.css
  src/Component/List/MyStockList.tsx
  src/Component/List/StockItem.tsx
  src/Component/List/StockItemStyle.css
  src/Component/List/StockList.tsx
  src/Pages/Nica.tsx
  src/Router.tsx
  src/constants/interface.ts
  src/data/data.ts
  src/img/logo/Discord.png
  src/img/logo/GitHub.png
  src/img/logo/Instagram.png
  src/img/logo/Line.png
  src/img/logo/Spotify.png
  src/img/logo/Telegram.png
  src/img/logo/TikTok.png
  src/img/logo/Twitter.png
  src/img/logo/Whatsapp.png
  src/img/logo/Youtube.png
  src/img/myPortfolioImg.png
  src/util/util.ts
Labels: feat

#11 Feature/elle
  package-lock.json
  package.json
  src/Component/Button/button.tsx
  src/Component/Chart/chart.tsx
  src/Component/Input/input.tsx
  src/Component/Modal/modal.tsx
  src/Component/Modal/modalStyle.ts
  src/Pages/home.tsx
  src/Styles/Fonts.ts
  src/Styles/button.ts
  src/Styles/input.ts
  src/constants/interface.ts
  src/fonts/fonts.css
Labels: feat

#12 Feature/lucy
  package-lock.json
  package.json
  src/Component/Dropdown/Dropdown.tsx
  src/Component/Layout/Header/BackHeader.tsx
  src/Component/Layout/Header/Header.tsx
  src/Component/Layout/Header/Logo.tsx
  src/Component/Layout/Header/Profile.tsx
  src/Component/Layout/Layout.tsx
  src/Component/Layout/NavBar/NavBar.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Pages/home.tsx
  src/Pages/portfolio.tsx
  src/Pages/searchStock.tsx
  src/Pages/skrrrGame.tsx
  src/Router.tsx
  src/constants/interface.ts
  src/img/backImg.png
  src/img/closeStatus.png
  src/img/home.png
  src/img/openStatus.png
  src/img/search.png
  src/img/shutUp.png
Labels: feat

#15 Feature/elle
  src/Component/List/MyStockItem.tsx
  src/Component/List/MyStockItemStyle.css
  src/Component/List/modalStyle.ts
  src/Component/Modal/modal.tsx
  src/Component/Modal/modalStyle.ts
  src/Pages/portfolio.tsx
  src/constants/interface.ts
Labels: feat

#13 Dev
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/Component/Button/button.tsx
  src/Component/Carousel/EmblaCarousel.tsx
  src/Component/Carousel/EmblaCarouselArrowButtons.tsx
  src/Component/Carousel/EmblaCarouselDotButton.tsx
  src/Component/Carousel/base.css
  src/Component/Carousel/embla.css
  src/Component/Chart/chart.tsx
  src/Component/Dropdown/Dropdown.tsx
  src/Component/Input/input.tsx
  src/Component/Layout/Header/BackHeader.tsx
  src/Component/Layout/Header/Header.tsx
  src/Component/Layout/Header/Logo.tsx
  src/Component/Layout/Header/Profile.tsx
  src/Component/Layout/Layout.tsx
  src/Component/Layout/NavBar/NavBar.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/List/MyStockItemStyle.css
  src/Component/List/MyStockList.tsx
  src/Component/List/StockItem.tsx
  src/Component/List/StockItemStyle.css
  src/Component/List/StockList.tsx
  src/Component/List/modalStyle.ts
  src/Component/Modal/modal.tsx
  src/Component/Modal/modalStyle.ts
  src/Component/SearchBar/SearchBar.tsx
  src/Pages/Nica.tsx
  src/Pages/home.tsx
  src/Pages/portfolio.tsx
  src/Pages/searchStock.tsx
  src/Pages/skrrrGame.tsx
  src/Router.tsx
  src/Styles/Fonts.ts
  src/Styles/button.ts
  src/Styles/input.ts
  src/constants/interface.ts
  src/data/data.ts
  src/fonts/fonts.css
  src/img/backImg.png
  src/img/closeStatus.png
  src/img/home.png
  src/img/logo/Discord.png
  src/img/logo/GitHub.png
  src/img/logo/Instagram.png
  src/img/logo/Line.png
  src/img/logo/Spotify.png
  src/img/logo/Telegram.png
  src/img/logo/TikTok.png
  src/img/logo/Twitter.png
  src/img/logo/Whatsapp.png
  src/img/logo/Youtube.png
  src/img/myPortfolioImg.png
  src/img/openStatus.png
  src/img/search.png
  src/img/shutUp.png
  src/util/util.ts
Labels: docs

#16 Update issue templates
  .github/ISSUE_TEMPLATE/기본-이슈-템플릿.md
Labels: docs

#17 Feat : news list
  src/Component/News/NewsItem.tsx
  src/Component/News/NewsItemStyle.css
  src/Component/News/NewsList.tsx
  src/Pages/Nica.tsx
  src/constants/interface.ts
  src/data/data.ts
Labels: feat

#18 Feature/elle
  package-lock.json
  package.json
  src/.env
  src/Component/GoogleLogin/callback.tsx
  src/Component/GoogleLogin/login.tsx
  src/Component/GoogleLogin/loginStyle.ts
  src/Component/Input/input.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/List/StockList.tsx
  src/Component/Modal/addStock.tsx
  src/Component/Modal/deleteProtfolio.tsx
  src/Component/Modal/modalStyle.ts
  src/Component/Modal/plusStock.tsx
  src/Component/Modal/stockSearch.tsx
  src/Pages/home.tsx
  src/Pages/login.tsx
  src/Router.tsx
  src/constants/interface.ts
  src/img/Logo.png
  src/img/Official Buttons/Sign in with Google/White/googleLogo.png
Labels: feat

#19 Feature/veronica
  package-lock.json
  package.json
  src/Component/Animation/HyperText.tsx
  src/Component/Carousel/embla.css
  src/Component/Modal/PfCreate.tsx
  src/Pages/Nica.tsx
  src/Pages/portfolio.tsx
  src/Styles/pfStyle.css
  src/img/portfolioImg.png
Labels: feat

#21 Feature/lucy
  src/App.tsx
  src/Component/Calculator/calculResult.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/Dropdown/Dropdown.tsx
  src/Component/Layout/Header/Logo.tsx
  src/Component/Layout/Header/Profile.tsx
  src/Component/Layout/Layout.tsx
  src/Component/Layout/NavBar/NavBar.tsx
  src/Component/List/StockItemStyle.css
  src/Component/News/NewsItemStyle.css
  src/Component/SearchBar/SearchBar.tsx
  src/Pages/home.tsx
  src/Pages/searchStock.tsx
  src/Pages/skrrrGame.tsx
  src/Pages/stockDetail.tsx
  src/Router.tsx
  src/constants/interface.ts
  src/custom.d.ts
Labels: feat

#22 Feature/elle
  src/Component/List/MyStockItem.tsx
  src/Component/Modal/addStock.tsx
  src/Component/Modal/stockSearch.tsx
  src/Component/Portfolio/pfStyle.css
  src/Component/Portfolio/portfolio.tsx
  src/Pages/home.tsx
  src/Pages/portfolio.tsx
  src/Router.tsx
  src/Styles/pfStyle.css
Labels: feat

#23 Feature/veronica
  src/Component/Modal/AddPortfolio.tsx
  src/Component/Modal/AddPortfolioStyle.css
  src/Pages/Nica.tsx
  src/img/Icon.png
  src/img/newPortfolio.png
Labels: feat

#25 Feat: 새로운 포트폴리오 만들기 모달창 + 연결 완
  .github/workflows/cicd.yml
  src/Component/Modal/AddPortfolio.tsx
  src/Component/Modal/PfCreate.tsx
  src/Component/Modal/addStock.tsx
  src/Component/Modal/modal.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Pages/Nica.tsx
  src/constants/interface.ts
Labels: feat

#26 Feat : swipe창 구현
  src/Component/Swipe/Swipe.tsx
  src/Component/Swipe/SwipeStyle.css
  src/Pages/Nica.tsx
Labels: feat

#27 Docs : 스와이프창 모달 연결
  src/Component/Modal/modal.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Component/Swipe/Swipe.tsx
  src/Pages/portfolio.tsx
Labels: feat

#28 Feat : css 버그 수정
  src/Component/Modal/AddPortfolioStyle.css
  src/Component/Swipe/SwipeStyle.css
Labels: feat

#30 Feature/elle
  package-lock.json
  package.json
  src/.env
  src/App.tsx
  src/Component/GoogleLogin/callback.tsx
  src/Component/GoogleLogin/login.tsx
  src/Component/Input/input.tsx
  src/Component/Layout/Header/Profile.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/Modal/AddPortfolio.tsx
  src/Component/Modal/deleteProtfolio.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Pages/login.tsx
  src/Pages/skrrrGame.tsx
  src/Router.tsx
  src/contexts/authContext.tsx
  src/img/GameLoadingPage.png
  src/img/SkerrImg.png
  src/index.tsx
Labels: docs, refactoring, feat, style

#31 Feat : 포트폴리오 라우터
  src/Component/Carousel/EmblaCarousel.tsx
  src/Component/Layout/Layout.tsx
  src/Component/Portfolio/PfCard.tsx
  src/Component/Portfolio/PfCardStyle.css
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Swipe/Swipe.tsx
  src/Component/Swipe/SwipeStyle.css
  src/Pages/PortfolioDetail.tsx
  src/Pages/PortfolioNo.tsx
  src/Router.tsx
Labels: feat

#32 Feature/lucy
  src/App.css
  src/Component/Button/button.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/Chart/chart.tsx
  src/Component/Dropdown/Dropdown.tsx
  src/Component/Layout/Header/BackHeader.tsx
  src/Component/Layout/Header/Header.tsx
  src/Component/Layout/Layout.tsx
  src/Pages/searchStock.tsx
  src/Pages/stockDetail.tsx
  src/constants/interface.ts
  src/img/calcul.png
Labels: feat, style

#35 Delete .github/workflows/cicd.yml
  .github/workflows/cicd.yml
Labels: fix

#33 Style : 디자인 수정
  src/Component/Calculator/calculator.tsx
  src/Component/Input/input.tsx
  src/Component/Modal/AddPortfolio.tsx
  src/Component/Modal/addStock.tsx
  src/Component/Modal/modalStyle.ts
  src/Component/Modal/plusStock.tsx
  src/Component/Modal/stockSearch.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/portfolio.tsx
  src/constants/interface.ts
Labels: refactoring, style

#36 Feature/lucy
  package-lock.json
  package.json
  src/Component/Button/Animation/HyperText.tsx
  src/Component/Calculator/calculResult.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/Layout/Layout.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Pages/home.tsx
  src/Pages/stockDetail.tsx
  src/img/backImg.png
Labels: feat, style

#37 Feat : pie chart
  package-lock.json
  package.json
  src/App.css
  src/Component/Chart/PieChart.tsx
  src/Component/Layout/Layout.tsx
  src/Component/List/StockList.tsx
  src/Pages/PortfolioDetail.tsx
  src/index.css
Labels: feat

#38 Feature/elle
  src/App.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/GoogleLogin/login.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/Modal/addStock.tsx
  src/Component/Modal/plusStock.tsx
Labels: 중복된 이슈, feat

#39 Dev
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/Chart/PieChart.tsx
  src/Component/GoogleLogin/login.tsx
  src/Component/Input/input.tsx
  src/Component/Layout/Layout.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/List/StockList.tsx
  src/Component/Modal/AddPortfolio.tsx
  src/Component/Modal/addStock.tsx
  src/Component/Modal/modalStyle.ts
  src/Component/Modal/plusStock.tsx
  src/Component/Modal/stockSearch.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Pages/PortfolioDetail.tsx
  src/constants/interface.ts
  src/index.css
Labels: feat

#40 Update calculator.tsx
  src/Component/Calculator/calculator.tsx
Labels: fix

#41 Style : 전체적인 레이아웃 수정
  src/App.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/Layout/Header/Header.tsx
  src/Component/Layout/Layout.tsx
Labels: style

#42 Update App.tsx
  src/App.tsx
Labels: 버그-심각

#43 Update App.tsx
  src/App.tsx
Labels: 버그-심각

#44 Feature/elle
  .github/ISSUE_TEMPLATE/기본-이슈-템플릿.md
  .github/workflows/deploy.yml
  Dockerfile
  nginx.conf
  package-lock.json
  package.json
  src/App.tsx
  src/Component/Button/Animation/HyperText.tsx
  src/Component/Calculator/calculResult.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/GoogleLogin/callback.tsx
  src/Component/Layout/Header/Header.tsx
  src/Component/Layout/Header/Logo.tsx
  src/Component/Layout/Layout.tsx
  src/Component/Layout/NavBar/NavBar.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Pages/home.tsx
  src/Pages/stockDetail.tsx
  src/Router.tsx
  src/img/backImg.png
Labels: fix

#45 Feat: donut chart
  src/App.tsx
  src/Component/Carousel/embla.css
  src/Component/Chart/PieChart.tsx
  src/Component/Layout/Layout.tsx
  src/Component/Swipe/SwipeStyle.css
  src/Pages/PortfolioDetail.tsx
Labels: feat

#46 Feature/lucy
  public/SkerrImg.png
  public/index.html
  src/App.tsx
  src/Component/Layout/Layout.tsx
  src/Component/List/StockList.tsx
  src/Component/News/NewsList.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Component/SearchBar/SearchBarStyle.ts
  src/Pages/home.tsx
  src/Pages/searchStock.tsx
  src/constants/interface.ts
Labels: docs, feat

#48 Update App.tsx
  src/App.tsx
Labels: fix

#47 Dev
  public/SkerrImg.png
  public/index.html
  src/App.tsx
  src/Component/Carousel/embla.css
  src/Component/Chart/PieChart.tsx
  src/Component/GoogleLogin/callback.tsx
  src/Component/Layout/Header/Logo.tsx
  src/Component/Layout/Layout.tsx
  src/Component/Layout/NavBar/NavBar.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/List/StockList.tsx
  src/Component/News/NewsList.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Component/SearchBar/SearchBarStyle.ts
  src/Component/Swipe/SwipeStyle.css
  src/Pages/PortfolioDetail.tsx
  src/Pages/home.tsx
  src/Pages/searchStock.tsx
  src/Router.tsx
  src/constants/interface.ts
Labels: fix

#49 Style : 전체적인 css 수정
  src/Component/Chart/PieChart.tsx
  src/Component/Layout/NavBar/NavBar.tsx
  src/Component/Swipe/Swipe.tsx
  src/Component/Swipe/SwipeStyle.css
  src/Pages/PortfolioDetail.tsx
Labels: feat

#50 Fix : 구글 로그인 수정
  src/App.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/GoogleLogin/callback.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/List/StockList.tsx
  src/Component/News/NewsList.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Pages/home.tsx
  src/Pages/searchStock.tsx
  src/contexts/authContext.tsx
Labels: fix

#51 Dev
  src/Component/Chart/PieChart.tsx
  src/Component/Layout/NavBar/NavBar.tsx
  src/Component/Swipe/Swipe.tsx
  src/Component/Swipe/SwipeStyle.css
  src/Pages/PortfolioDetail.tsx
Labels: fix

#52 Docs: 로그인 수정, 뉴스 api 수정
  src/App.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/GoogleLogin/callback.tsx
  src/Component/GoogleLogin/login.tsx
  src/Component/Layout/Header/Profile.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/List/StockList.tsx
  src/Component/News/NewsList.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Pages/home.tsx
  src/Pages/searchStock.tsx
  src/contexts/authContext.tsx
Labels: docs, fix

#54 Update index.tsx
  src/index.tsx
Labels: 버그-심각

#56 Update index.tsx
  src/index.tsx
Labels: 버그-심각

#57 Feature/elle
  src/Component/List/MyStockItem.tsx
  src/Component/Portfolio/PfCreate.tsx
Labels: fix

#58 Feat : portfolio 조회
  package.json
  src/Component/Button/Animation/HyperText.tsx
  src/Component/Portfolio/pfStyle.css
  src/Component/Portfolio/portfolio.tsx
  src/util/util.ts
Labels: feat

#59 Feat : portfolio Detail 조회
  src/Component/Carousel/EmblaCarousel.tsx
  src/Component/Chart/PieChart.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/List/MyStockList.tsx
  src/Component/Portfolio/PfCard.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Component/Swipe/Swipe.tsx
  src/Pages/Nica.tsx
  src/Pages/PortfolioDetail.tsx
  src/Pages/PortfolioDetailPage.tsx
  src/Router.tsx
  src/constants/interface.ts
Labels: feat

#60 Feature/lucy
  package.json
  src/Component/Calculator/calculator.tsx
  src/Component/Dropdown/Dropdown.tsx
  src/Component/List/StockItem.tsx
  src/Component/List/StockList.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Component/SearchBar/SearchBarStyle.ts
  src/Pages/home.tsx
  src/Pages/searchStock.tsx
  src/Pages/stockDetail.tsx
  src/Pages/stockDetail/stockDetail.tsx
  src/Pages/stockDetail/stockDetailStyle.ts
  src/Router.tsx
  src/constants/interface.ts
Labels: fix, feat

#62 Docs : 로그인 성공
  src/App.tsx
  src/Component/GoogleLogin/callback.tsx
  src/Component/GoogleLogin/login.tsx
  src/Component/Layout/Header/Profile.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/List/StockList.tsx
  src/Component/Modal/AddPortfolio.tsx
  src/Component/Modal/addStock.tsx
  src/Component/Modal/plusStock.tsx
  src/Component/News/NewsList.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Pages/home.tsx
  src/contexts/authContext.tsx
Labels: refactoring, fix, feat

#63 Feature/lucy
  src/Component/List/Data/stockData.tsx
  src/Component/List/Data/stockDataList.tsx
  src/Component/List/StockItem.tsx
  src/Component/List/StockList.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Pages/home.tsx
  src/Pages/searchStock.tsx
  src/Pages/stockDetail/stockDetail.tsx
  src/constants/interface.ts
  src/index.tsx
  src/util/util.ts
Labels: fix, feat

#64 Feature/elle
  src/Component/Calculator/calculator.tsx
  src/Component/List/Data/stockData.tsx
  src/Pages/searchStock.tsx
  src/Pages/stockDetail/stockDetail.tsx
  src/constants/interface.ts
Labels: fix, feat

#65 Feat : util 적용
  src/Component/Button/Animation/HyperText.tsx
  src/Component/Carousel/EmblaCarousel.tsx
  src/Component/List/MyStockList.tsx
  src/Component/Portfolio/PfCard.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Pages/home.tsx
  src/util/util.ts
Labels: feat

#66 Feat : 차트 그리기 성공~
  package-lock.json
  package.json
  src/Component/Button/Animation/rotatioin.tsx
  src/Component/Chart/chart.tsx
  src/Pages/stockDetail/stockDetail.tsx
  src/constants/interface.ts
Labels: fix, feat

#67 Feature/lucy - 스껄 계산기
  package-lock.json
  package.json
  src/Component/Calculator/calculResult.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/Dropdown/Dropdown.tsx
  src/Component/List/Data/stockData.tsx
  src/Component/List/Data/stockDataList.tsx
  src/Component/List/StockItemStyle.css
  src/Component/Portfolio/portfolio.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Component/SearchBar/SearchBarStyle.ts
  src/Pages/home.tsx
  src/Pages/searchStock.tsx
  src/Pages/stockDetail/stockDetail.tsx
  src/Pages/stockDetail/stockDetailStyle.ts
  src/Styles/button.ts
  src/constants/interface.ts
Labels: fix, feat

#68 차트 한글로 변경 성공~
  src/Component/Calculator/calculator.tsx
  src/Component/Chart/chart.tsx
  src/Component/Chart/chartStyle.ts
  src/Component/GoogleLogin/loginStyle.ts
  src/Component/Layout/Header/Profile.tsx
  src/Component/Layout/Layout.tsx
  src/Pages/404/loginPage.tsx
  src/Pages/404/noUser.tsx
  src/Pages/home.tsx
  src/Pages/stockDetail/stockDetail.tsx
  src/Router.tsx
  src/constants/interface.ts
Labels: fix

#69 Feat : 포트폴리오 추가 수정
  package-lock.json
  package.json
  src/Component/Carousel/EmblaCarousel.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/List/MyStockList.tsx
  src/Component/Modal/AddPortfolio.tsx
  src/Component/Modal/deleteProtfolio.tsx
  src/Component/Modal/plusStock.tsx
  src/Component/Portfolio/PfCard.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Component/Swipe/Swipe.tsx
  src/store/usePortfolioStore.ts
  src/util/util.ts
Labels: feat

#70 Feature/lucy - api 요청 url 수정
  package.json
  src/.env
  src/Component/Calculator/calculResult.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/Dropdown/Dropdown.tsx
  src/Component/GoogleLogin/callback.tsx
  src/Component/GoogleLogin/login.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/Modal/addStock.tsx
  src/Component/Modal/stockSearch.tsx
  src/Component/News/NewsList.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Pages/home.tsx
  src/Pages/searchStock.tsx
  src/Pages/skrrrGame.tsx
  src/Pages/stockDetail/stockDetail.tsx
  src/constants/interface.ts
Labels: docs, style

#72 Feat : 주식종목 리랜더링 없이
  package-lock.json
  package.json
  src/Component/List/MyStockItem.tsx
  src/Component/Modal/plusStock.tsx
  src/store/usePortfolioStore.ts
Labels: feat

#73 Feature/lucy
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/Component/News/NewsItem.tsx
  src/Router.tsx
Labels: refactoring, fix, feat

#75 Fix : useEffect top level에서 사용 불가 오류 수정
  src/Router.tsx
Labels: fix

#76 Docs : 설정 .. 주석처리.. 내일까지 하겠읍니다..
  package-lock.json
  package.json
  src/Router.tsx
  src/index.tsx
Labels: docs

#101 Feature/lucy - api url 수정 반영
  .gitignore
  package-lock.json
  package.json
  src/Component/Calculator/calculator.tsx
  src/Component/GoogleLogin/callback.tsx
  src/Component/GoogleLogin/login.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/Modal/addStock.tsx
  src/Component/Modal/stockSearch.tsx
  src/Component/News/ noNews.tsx
  src/Component/News/NewsList.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Pages/home.tsx
  src/Pages/searchStock.tsx
  src/Pages/stockDetail/stockDetail.tsx
  src/Router.tsx
Labels: chore

#110 Fix : API URL 안먹는 부분 백틱으로 수정
  src/Component/GoogleLogin/callback.tsx
  src/Component/GoogleLogin/login.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/portfolio.tsx
Labels: fix

#111 Fix : API URL 안먹는 부분 백틱으로 수정
  src/Component/GoogleLogin/callback.tsx
  src/Component/GoogleLogin/login.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/portfolio.tsx
Labels: fix

#116 Feature/lucy
  .gitignore
  src/Component/Chart/chart.tsx
  src/Component/GoogleLogin/login.tsx
  src/Component/Input/input.tsx
  src/Component/Layout/Header/Profile.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/Modal/addStock.tsx
  src/Component/Modal/deleteProtfolio.tsx
  src/Component/Modal/stockSearch.tsx
  src/Component/News/NewsItem.tsx
  src/Component/News/NewsItemStyle.css
  src/Component/News/NewsList.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Component/Swipe/Swipe.tsx
  src/Router.tsx
  src/contexts/authContext.tsx
  src/store/usePortfolioStore.ts
Labels: fix

#123 Feature/lucy
  package-lock.json
  package.json
  public/index.html
  src/Component/Layout/Header/Profile.tsx
  src/Component/News/ noNews.tsx
  src/Component/News/NewsList.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Pages/404/noUser.tsx
  src/Router.tsx
  src/index.tsx
Labels: docs, fix, chore, feat

#112 Feature/veronica
  src/Component/Carousel/embla.css
  src/Component/Input/input.tsx
  src/Component/Modal/AddPortfolio.tsx
  src/Component/Modal/addStock.tsx
  src/Component/Modal/stockSearch.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Router.tsx
  src/constants/interface.ts
  src/store/usePortfolioStore.ts
Labels: fix

#125 Feature/lucy
  src/Component/Calculator/calculResult.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/Modal/addStock.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Component/SearchBar/SearchBarStyle.ts
  src/constants/interface.ts
Labels: fix

#133 Feature/lucy
  src/Component/Calculator/calculator.tsx
  src/Component/Chart/chart.tsx
  src/Component/Input/input.tsx
  src/Component/News/NewsItem.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
Labels: fix, chore, feat

#134 Fix : 상승 하락 색깔조절 #84
  src/Component/Carousel/EmblaCarousel.tsx
  src/Component/List/Data/stockData.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/Portfolio/PfCard.tsx
  src/Component/Portfolio/portfolio.tsx
  src/util/util.ts
Labels: fix, style

#136 Fix : myStockItem %조절 #135
  src/Component/List/MyStockItemStyle.css
  src/Component/Portfolio/PfCard.tsx
  src/Component/Portfolio/PfCardStyle.css
Labels: fix, style

#138 Fix : 입력값 제한 #130
  src/Component/List/MyStockItem.tsx
  src/Component/Modal/plusStock.tsx
Labels: fix, style

#140 Feat : 포트폴리오 삭제버튼 추가
  src/Component/Carousel/EmblaCarousel.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
Labels: feat

#141 Feature/lucy
  src/Component/Chart/chart.tsx
  src/Component/Chart/chartStyle.ts
  src/Component/Modal/AddPortfolio.tsx
  src/Component/Modal/modalStyle.ts
  src/Component/News/NewsList.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Pages/PortfolioNo.tsx
Labels: fix, feat

#142 Fix : 포트폴리오 유무에 따른 리다이렉팅 수정 #113 #114
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Pages/portfolio.tsx
  src/Router.tsx
  src/store/usePortfolioStore.ts
Labels: fix, feat

#145 Dev
  .github/workflows/deploy.yml
Labels: 버그-심각

#148 Dev
  .github/workflows/deploy.yml
  src/Component/Chart/chart.tsx
Labels: fix

#155 Docs : console 삭제
  src/Component/Calculator/calculResult.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/Carousel/EmblaCarousel.tsx
  src/Component/GoogleLogin/callback.tsx
  src/Component/GoogleLogin/login.tsx
  src/Component/Layout/NavBar/NavBar.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/Modal/AddPortfolio.tsx
  src/Component/Modal/addStock.tsx
  src/Component/Modal/stockSearch.tsx
  src/Component/News/NewsList.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Component/Swipe/Swipe.tsx
  src/Pages/home.tsx
  src/Pages/portfolio.tsx
  src/Pages/searchStock.tsx
  src/Pages/stockDetail/stockDetail.tsx
  src/contexts/authContext.tsx
Labels: docs

#158 Style : 미디어쿼리 적용
  .env
  package-lock.json
  package.json
  src/Component/Chart/chart.tsx
  src/Component/Layout/Header/Header.tsx
  src/Component/Layout/Layout.tsx
  src/Component/Layout/NavBar/NavBar.tsx
  src/Component/List/Data/stockDataList.tsx
  src/Component/SearchBar/SearchBarStyle.ts
  src/Pages/home.tsx
  src/Styles/GlobalStyles.ts
Labels: style

#159 Feat : 포트폴리오 삭제버튼 완성
  src/Component/Button/DeleteButton.tsx
  src/Component/Button/DeleteButtonStyle.css
  src/Component/Modal/AddPortfolio.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
Labels: feat

#160 Fix : 포트폴리오 삭제 404 오류
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
Labels: fix

#161 Feature/elle
  src/Component/Calculator/calculator.tsx
  src/Component/Input/input.tsx
  src/Component/Modal/AddPortfolio.tsx
  src/Component/Modal/stockSearch.tsx
  src/Component/News/ noNews.tsx
  src/Component/News/NewsList.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Pages/404/errorPage.tsx
  src/Pages/home.tsx
  src/Pages/portfolio.tsx
  src/Pages/searchStock.tsx
  src/Pages/stockDetail/stockDetail.tsx
  src/Router.tsx
Labels: fix

#163 Delete .env
  .env
Labels: fix

#164 Fix : 버그 수정
  src/Component/News/NewsList.tsx
Labels: fix

#166 Feature/elle
  src/Component/Button/Animation/HyperText.tsx
  src/Component/Button/DeleteButton.tsx
  src/Component/Button/DeleteButtonStyle.css
  src/Component/Carousel/EmblaCarousel.tsx
  src/Component/Carousel/embla.css
  src/Component/Chart/PieChart.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/pfStyle.css
  src/Component/Portfolio/portfolio.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Component/SearchBar/SearchBarStyle.ts
  src/Component/Swipe/Swipe.tsx
Labels: fix, style

#168 Feature/elle
  src/Pages/home.tsx
Labels: style

#169 Feature/elle
  src/Component/Button/Animation/rotatioin.tsx
  src/Component/Button/button.tsx
  src/Component/Calculator/calculResult.tsx
  src/Component/Calculator/calculator.tsx
  src/Component/Modal/modal.tsx
  src/Component/News/ noNews.tsx
  src/Component/News/NewsList.tsx
  src/Component/Portfolio/PfCreate.tsx
  src/Pages/404/errorPage.tsx
  src/Pages/home.tsx
  src/constants/interface.ts
Labels: fix

#170 Style : 포트폴리오 상세 스타일 수정
  src/Component/Carousel/EmblaCarousel.tsx
  src/Component/Carousel/embla.css
Labels: style

#173 Style : 모바일 화면 크기 조정 / 포폴 상세 삭제 버튼 수정
  src/Component/Button/DeleteButton.tsx
  src/Component/Carousel/EmblaCarousel.tsx
  src/Component/Carousel/embla.css
  src/Component/List/Data/stockDataList.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/Modal/AddPortfolio.tsx
  src/Component/Modal/modal.tsx
  src/Component/Modal/modalStyle.ts
  src/Component/Portfolio/PfCard.tsx
  src/Component/Portfolio/PfCardStyle.css
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Component/Swipe/Swipe.tsx
  src/Component/Swipe/SwipeStyle.css
  src/util/util.ts
Labels: style

#175 Fix : portfolio detail 404 에러 수정
  src/Component/Carousel/EmblaCarousel.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
Labels: fix

#176 Style : 모달창 범위 수정
  src/Component/Modal/modal.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
Labels: style

#177 Dev
  src/Component/Modal/modal.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
Labels: fix

#178 Fix : css수정
  src/Component/Button/DeleteButtonStyle.css
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Swipe/SwipeStyle.css
  src/Pages/PortfolioDetailPage.tsx
Labels: fix
