Repository 100-hours-a-week/5-team-HRTH-ustock-fe, pull requests merged in 2024-09, with the labels that each got.

#179 Feature/veronica
  src/Component/Chart/chart.tsx
Labels: fix

#181 Feature/lucy
  src/Component/Calculator/calculator.tsx
  src/Component/Chart/chart.tsx
  src/Component/Layout/NavBar/NavBar.tsx
  src/Component/Modal/stockSearch.tsx
  src/Component/News/NewsItem.tsx
  src/Component/News/NewsList.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Pages/home.tsx
  src/Pages/portfolio.tsx
  src/Pages/searchStock.tsx
  src/constants/interface.ts
  src/img/chart.png
  src/img/home.png
  src/img/loudly.png
  src/img/portfolio.png
  src/img/shutUp.png
  src/img/skrr_calculator.png
Labels: fix, style

#182 Feature/lucy - 게임 라우터 설정
  src/Component/Calculator/calculator.tsx
  src/Component/Chart/chart.tsx
  src/Component/Layout/NavBar/NavBar.tsx
  src/Component/Modal/stockSearch.tsx
  src/Component/News/NewsItem.tsx
  src/Component/News/NewsList.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Pages/game/gameStocks.tsx
  src/Pages/game/infoPage.tsx
  src/Pages/game/playPage.tsx
  src/Pages/game/playResult.tsx
  src/Pages/game/rank.tsx
  src/Pages/game/totalResult.tsx
  src/Pages/home.tsx
  src/Pages/portfolio.tsx
  src/Pages/searchStock.tsx
  src/Router.tsx
  src/constants/interface.ts
  src/img/chart.png
  src/img/home.png
  src/img/loudly.png
  src/img/portfolio.png
  src/img/shutUp.png
  src/img/skrr_calculator.png
Labels: chore

#183 Feature/lucy
  src/Pages/game/gameStocks.tsx
  src/Pages/game/infoPage.tsx
  src/Pages/game/playPage.tsx
  src/Pages/game/playResult.tsx
  src/Pages/game/rank.tsx
  src/Pages/game/totalResult.tsx
  src/Router.tsx
Labels: fix

#185 Chore : 센트리 설정 변경, 게임용 헤더적용을 위한 라우터 수정 및 게임용 헤더 생성
  public/index.html
  src/Component/Game/GameHeader.tsx
  src/Component/Layout/Layout.tsx
  src/Pages/game/totalResult.tsx
  src/Router.tsx
  src/constants/interface.ts
  src/index.tsx
Labels: chore

#187 Feat : 년도별 게임 화면
  src/Component/Game/GameButtons.tsx
  src/Component/Game/GameButtonsStyle.css
  src/Component/Game/GameHeader.tsx
  src/Component/Game/GameMoney.tsx
  src/Component/Game/GameTradeSwipe.tsx
  src/Component/Game/GameTradeSwipeStyle.css
  src/Component/Game/StocksTable.tsx
  src/Component/Game/StocksTableStyle.css
  src/Component/Game/TradeChoice.tsx
  src/Component/Game/TradeChoiceStyle.css
  src/Component/Game/TradeConfirmModal.tsx
  src/Pages/game/infoPage.tsx
  src/Pages/game/playPage.tsx
  src/Pages/game/totalResult.tsx
  src/constants/interface.ts
  src/data/data.json
  src/img/GameButton/info.png
  src/img/GameButton/infoImg.png
  src/img/GameButton/pass.png
  src/img/GameButton/passImg.png
  src/img/GameButton/trade.png
  src/img/GameButton/tradeImg.png
  src/util/gameUtil.ts
Labels: feat

#196 Feature/elle
  src/Component/Button/DeleteButton2.tsx
  src/Component/Chart/chart.tsx
  src/Component/Chart/chartStyle.ts
  src/Component/Modal/addStock.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
Labels: feat

#197 Feat : 메인 & 정보거래소 api 연결 / 튜토리얼 생성
  .gitignore
  public/index.html
  src/Component/Dropdown/gameDropdown.tsx
  src/Game/Main/gameStart.tsx
  src/Game/Main/mainStyle.css
  src/Game/Main/styleMain.ts
  src/Game/Shop/arrayUtils.ts
  src/Game/Shop/ingredient.ts
  src/Game/Shop/shop.tsx
  src/Game/Shop/shopStyle.ts
  src/Game/Tutorial/Portal.tsx
  src/Game/Tutorial/tuto.css
  src/Game/Tutorial/tutorial.tsx
  src/Game/exchangeStoreMain.tsx
  src/Pages/game/infoPage.tsx
  src/Pages/game/playPage.tsx
  src/Pages/skrrrGame.tsx
  src/Router.tsx
  src/Styles/button.ts
  src/Styles/input.ts
  src/constants/interface.ts
  src/img/fly_parrot.png
  src/img/parrot.png
  src/store/stockContext.tsx
Labels: feat

#198 Feature/veronica
  package-lock.json
  package.json
  src/Component/Game/Animation - 1726124464283.json
  src/Component/Game/GameMoney.tsx
  src/Component/Game/GameTradeSwipe.tsx
  src/Component/Game/StocksTable.tsx
  src/Component/Game/StocksTableStyle.css
  src/Component/Game/TradeChoiceStyle.css
  src/Game/Main/gameStart2.tsx
  src/Pages/game/Animation.json
  src/Pages/game/HappyNewYearModal.tsx
  src/Pages/game/playPage.tsx
  src/Pages/skrrrGame.tsx
  src/Router.tsx
  src/constants/interface.ts
  src/util/gameUtil.ts
Labels: feat

#199 Feature/lucy
  package-lock.json
  package.json
  public/index.html
  src/Component/Chart/chartStyle.ts
  src/Component/Game/GameNews/gameNewsItem.tsx
  src/Component/Game/GameNews/gmaeNewsList.tsx
  src/Component/Game/Rank/rankBox.tsx
  src/Component/Game/Rank/rankBoxStyle.ts
  src/Component/Game/Rank/rankList.tsx
  src/Component/Game/Rank/saySkrr.tsx
  src/Component/GameCarousel/carouselItem.tsx
  src/Component/GameCarousel/gameCarousel.tsx
  src/Component/GameCarousel/gameChart.tsx
  src/Component/GameCarousel/gameNews.tsx
  src/Component/GameCarousel/gameNewsList.tsx
  src/Component/News/NewsItemStyle.css
  src/Component/News/NewsList.tsx
  src/Pages/game/gameStocks.tsx
  src/Pages/game/rank.tsx
  src/Pages/game/totalResult.tsx
  src/Router.tsx
  src/constants/interface.ts
  src/img/bronzeMedal.png
  src/img/goldMedal.png
  src/img/silverMedal.png
  src/img/speechBubble.png
  tsconfig.json
Labels: feat

#200 Feat : 거래 스와이프 ux개선
  src/Component/Game/GameMoney.tsx
  src/Component/Game/GameTradeSwipe.tsx
  src/Pages/game/playPage.tsx
Labels: feat

#201 Feature/elle
  package-lock.json
  src/Component/Game/GameButtons.tsx
  src/Component/Game/GameMoney.tsx
  src/Component/Game/GameTradeSwipe.tsx
  src/Game/Main/gameStart.tsx
  src/Game/Main/styleMain.ts
  src/Game/Navigation/prevent.tsx
  src/Game/Navigation/preventBack.tsx
  src/Game/Shop/exchangeStoreMain.tsx
  src/Game/Shop/ingredient.ts
  src/Game/Shop/shop.tsx
  src/Game/Tutorial/ex.tsx
  src/Game/Tutorial/exStyle.scss
  src/Game/Tutorial/tuto.css
  src/Game/Tutorial/tutorial.tsx
  src/Pages/404/noUser.tsx
  src/Pages/game/gameStyle.css
  src/Pages/game/infoPage.tsx
  src/Pages/game/playPage.tsx
  src/Pages/skrrrGame.tsx
  src/Router.tsx
  src/img/stocklistImg.png
  src/store/usePortfolioStore.ts
Labels: feat

#202 Feat : 예수금 보여주기
  src/Component/Game/GameButtons.tsx
  src/Component/Game/GameTradeSwipe.tsx
  src/Pages/game/playPage.tsx
Labels: feat

#203 Feature/elle
  src/Component/Game/GameTradeSwipe.tsx
  src/Pages/game/playPage.tsx
Labels: fix

#204 Feature/lucy
  package-lock.json
  package.json
  public/index.html
  src/Component/Dropdown/gameDropdown.tsx
  src/Component/Game/GameMoney.tsx
  src/Component/Game/GameTradeSwipe.tsx
  src/Component/Game/Rank/rankBox.tsx
  src/Component/GameCarousel/carouselItem.tsx
  src/Component/GameCarousel/gameCarousel.tsx
  src/Component/GameCarousel/gameNewsList.tsx
  src/Component/List/MyStockItem.tsx
  src/Component/List/StockItem.tsx
  src/Component/Portfolio/PfCard.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Component/Portfolio/portfolio.tsx
  src/Component/Swipe/Swipe.tsx
  src/Game/Main/gameStart.tsx
  src/Game/Main/gameStart2.tsx
  src/Game/Shop/shop.tsx
  src/Game/Tutorial/ex.tsx
  src/Pages/game/gameStocks.tsx
  src/Pages/game/playPage.tsx
  src/Pages/game/playResult.tsx
  src/Pages/game/rank.tsx
  src/Pages/game/totalResult.tsx
  src/Router.tsx
  src/constants/interface.ts
  src/index.tsx
  src/store/usePortfolioStore.ts
Labels: docs, fix, feat

#205 Fix : 이슈 해결
  src/Game/Main/BentoBar/bentoBar.tsx
  src/Game/Main/BentoBar/bentoStyle.ts
  src/Game/Main/gameStart.tsx
  src/Game/Main/gameStart2.tsx
  src/Game/Main/styleMain.ts
  src/Game/Tutorial/ex.tsx
  src/Game/Tutorial/exStyle.scss
  src/Pages/game/gameStocks.tsx
  src/Pages/game/playPage.tsx
  src/Pages/game/rank.tsx
  src/Pages/game/totalResult.tsx
  src/Pages/skrrrGame.tsx
Labels: fix

#206 Feature/lucy
  src/Component/Game/GameMoney.tsx
  src/Component/Game/gameCurrentResult.tsx
  src/Component/Game/gameHoldingsView.tsx
  src/Component/Game/gameViewTab.tsx
  src/Pages/game/playPage.tsx
Labels: docs

#207 Feature/lucy
  src/Component/Game/gameCurrentResult.tsx
  src/Component/Game/gameViewTab.tsx
  src/Pages/game/playPage.tsx
  src/store/stockContext.tsx
Labels: fix, feat

#209 Feature/elle
  package-lock.json
  package.json
  src/Game/Loading/gameLoading.json
  src/Game/Loading/loading.tsx
  src/Game/Loading/mario.json
  src/Game/Main/BentoBar/bentoBar.tsx
  src/Game/Main/gameStart.tsx
  src/Game/Tutorial/ex.tsx
  src/Game/Tutorial/roll.tsx
  src/Pages/game/playPage.tsx
  src/img/tutorialImg.png
Labels: feat

#210 Feature/lucy
  src/Component/Game/GameTradeSwipe.tsx
  src/Component/Game/Rank/rankList.tsx
  src/Component/Game/gameCurrentResult.tsx
  src/Component/Game/gameHoldingsView.tsx
  src/Pages/game/playPage.tsx
  src/Pages/game/rank.tsx
  src/Pages/game/totalResult.tsx
  src/Router.tsx
Labels: docs, feat

#211 Feature/elle
  src/Component/Dropdown/gameDropdown.tsx
  src/Component/Dropdown/gameStyle.ts
  src/Game/Main/BentoBar/bentoBar.tsx
  src/Game/Navigation/prevent.tsx
  src/Game/Navigation/preventBack.tsx
  src/Game/Tutorial/ex.tsx
  src/Pages/game/playPage.tsx
Labels: fix

#212 Fix : interim 모달 순서 수정
  src/Component/Game/GameTradeSwipe.tsx
  src/Component/Game/TradeChoice.tsx
  src/Pages/game/playPage.tsx
Labels: fix

#213 Feature/lucy
  src/Component/Game/Rank/rankBox.tsx
  src/Component/Game/Rank/rankBoxStyle.ts
  src/Component/Game/Rank/rankList.tsx
  src/Component/Game/Rank/saySkrr.tsx
  src/Pages/game/totalResult.tsx
Labels: fix

#214 Feature/elle
  src/Pages/game/playPage.tsx
Labels: fix

#215 Feature/elle
  src/Pages/game/playPage.tsx
Labels: 버그-일반

#223 Feature/elle
  src/Game/Loading/gameLoading.json
  src/Game/Loading/progressBar.tsx
  src/Game/Main/gameStart.tsx
  src/Game/Shop/shop.tsx
  src/Pages/game/playPage.tsx
Labels: feat

#225 Feature/elle
  src/Component/Game/GameHeader.tsx
  src/Game/Loading/loading.tsx
  src/Game/Loading/progressBar.tsx
  src/Game/Main/ex.text
  src/Game/Tutorial/Portal.tsx
  src/Game/Tutorial/ex.tsx
  src/Game/Tutorial/exStyle.scss
  src/Game/Tutorial/roll.tsx
  src/Game/Tutorial/rule.tsx
  src/Game/Tutorial/튜토리얼아까워.text
  src/Pages/game/playPage.tsx
  src/img/Tutotial.png
  src/img/role.png
  src/img/tutorialImg.png
Labels: fix

#226 Feat : 마지막 턴에 거래 안되게 하기
  src/Component/Game/GameButtons.tsx
  src/Component/Game/GameButtonsStyle.css
  src/Component/Game/PassConfirmModal.tsx
  src/Game/Loading/loading.tsx
  src/Pages/game/playPage.tsx
Labels: feat

#227 Fix : 튜토리얼 해당하지 않은 페이지 삭제
  src/Component/Game/GameHeader.tsx
Labels: fix

#228 Fix : swipe 오류 수정
  src/Component/Game/GameTradeSwipe.tsx
  src/Component/Game/StocksTable.tsx
  src/Component/Game/TradeConfirmModal.tsx
  src/Game/Main/BentoBar/bentoStyle.ts
  src/Pages/game/playPage.tsx
  src/constants/interface.ts
  src/util/gameUtil.ts
Labels: fix

#229 Feature/lucy
  src/Component/Button/button.tsx
  src/Component/Chart/chart.tsx
  src/Component/Dropdown/Dropdown.tsx
  src/Component/Game/GameHeader.tsx
  src/Component/Game/GameMoney.tsx
  src/Component/Game/GameNews/gameNewsItem.tsx
  src/Component/Game/GameNews/gmaeNewsList.tsx
  src/Component/Game/GameTradeSwipe.tsx
  src/Component/Game/Rank/rankBox.tsx
  src/Component/Game/Rank/rankBoxStyle.ts
  src/Component/GoogleLogin/loginStyle.ts
  src/Component/Layout/Header/Header.tsx
  src/Component/Layout/Header/Profile.tsx
  src/Component/Layout/NavBar/NavBar.tsx
  src/Component/News/NewsItem.tsx
  src/Component/News/NewsList.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Game/Loading/progressBar.tsx
  src/Game/Shop/shop.tsx
  src/Game/Tutorial/rule.tsx
  src/Pages/404/noUser.tsx
  src/Pages/game/infoPage.tsx
  src/Pages/game/playPage.tsx
  src/Pages/game/rank.tsx
  src/Pages/game/totalResult.tsx
  src/Pages/home.tsx
  src/Pages/homeStyle.ts
  src/Pages/stockDetail/stockDetailStyle.ts
  src/index.tsx
  src/store/useGameStore.ts
  src/util/gameUtil.ts
Labels: docs, fix, feat, style

#230 Feature/elle
  src/Game/Shop/exchangeStoreMain.tsx
  src/Game/Shop/hintshop.tsx
  src/Game/Shop/ingredient.ts
  src/Game/Shop/shop.tsx
  src/store/hintStore.tsx
Labels: fix, feat

#231 Feature/elle
  src/Game/Shop/shop.tsx
  src/Pages/game/playPage.tsx
  src/store/hintStore.tsx
Labels: fix, feat

#245 Feature/elle
  src/Component/Chart/chart.tsx
  src/Component/Dropdown/gameDropdown.tsx
  src/Component/Dropdown/gameStyle.ts
  src/Component/Layout/Layout.tsx
  src/Game/Main/BentoBar/bentoBar.tsx
  src/Game/Main/BentoBar/bentoStyle.ts
  src/Game/Shop/exchangeStoreMain.tsx
  src/Game/Shop/hintshop.tsx
  src/Game/Shop/shop.tsx
  src/Pages/game/gameStocks.tsx
  src/Pages/game/rank.tsx
  src/Pages/game/totalResult.tsx
Labels: fix, style

#247 Feature/veronica
  src/Component/Game/GameMoney.tsx
  src/Component/Game/GameTradeSwipe.tsx
  src/Component/Game/StocksTable.tsx
  src/Component/Game/TradeChoice.tsx
  src/Component/Modal/modal.tsx
  src/Game/Main/gameStart.tsx
  src/Game/Tutorial/rule.tsx
  src/Pages/game/playPage.tsx
  src/store/useSwipeStore.tsx
Labels: fix

#246 Fix : feature/elle
  src/Component/Button/button.tsx
  src/Component/Chart/chart.tsx
  src/Component/Layout/Layout.tsx
  src/Game/Shop/shop.tsx
  src/constants/interface.ts
Labels: fix

#250 Fix : css 수정
  src/Component/Game/TradeChoice.tsx
Labels: fix
