Repository 100-hours-a-week/5-team-HRTH-ustock-fe, pull requests merged in 2024-10, with the labels that each got.

#252 Fix : css 수정
  src/Component/Game/GameTradeSwipe.tsx
  src/Component/Game/StocksTableStyle.css
Labels: style

#251 Style : 프로그래스바 위치 수정
  src/Game/Loading/progressBar.tsx
Labels: style

#253 Feature/veronica
  src/Component/Game/GameTradeSwipe.tsx
  src/Component/Game/StocksTableStyle.css
  src/Component/Game/TradeChoice.tsx
Labels: fix

#254 Feature/lucy
  package-lock.json
  package.json
  src/Component/Game/GameMoney.tsx
  src/Component/Game/GameTradeSwipe.tsx
  src/Component/GameCarousel/gameCarousel.tsx
  src/Pages/game/gameStocks.tsx
  src/Pages/game/playPage.tsx
  src/Pages/game/totalResult.tsx
Labels: fix, feat

#260 Lucy726j patch 3
  README.md
Labels: docs

#261 Feature/veronica
  src/Component/Chart/PieChart.tsx
  src/Component/Game/GameTradeSwipe.tsx
  src/Component/Game/TradeChoice.tsx
  src/Component/Game/gameHoldingsView.tsx
  src/Component/Portfolio/PortfolioDetail.tsx
  src/Pages/game/playPage.tsx
Labels: fix

#264 Fix : 종목 안불러와지는 이슈 수정
  src/Component/Dropdown/gameDropdown.tsx
  src/Component/Game/StocksTable.tsx
  src/Component/SearchBar/SearchBar.tsx
  src/Game/Main/gameStart.tsx
  src/Pages/game/playPage.tsx
  src/store/stockContext.tsx
Labels: fix

#268 Feature/veronica
  README.md
  src/Component/Game/StocksTable.tsx
  src/Pages/game/playPage.tsx
Labels: docs

#271 Update README.md
  README.md
Labels: docs
